### ISSUE TITLE
PayPal Plus - change available payment methods

### ISSUE THREAD

**Issue by elbsurfer** [shopwareLabs/SwagPaymentPaypalPlus#1]
Hello,
I want to change the selection of payment methods which are selectable by the customer, but I see that the relevant code section in the file paypal_form.js has been commented.

Why is this the case and how can I change the available payment methods for PayPal plus?

**Comment by mitelg** [comment]
Hi @elbsurfer,
the Paypal Plus plugin currently does not support displaying third party payment methods within the ifrme.
The customer is still able to select other payments than PPPlus on the /checkout/shippingPayment page.
